apiVersion: v1
kind: Namespace
metadata:
  name: openbkn-samples
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bkn-sample-studio
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: bkn-sample-studio
  namespace: openbkn-samples
rules:
  - apiGroups: [""]
    resources: ["secrets", "services"]
    verbs: ["get", "list", "create", "update", "patch"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
  - apiGroups: ["apps"]
    resources: ["statefulsets"]
    verbs: ["get", "list", "create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bkn-sample-studio
  namespace: openbkn-samples
subjects:
  - kind: ServiceAccount
    name: bkn-sample-studio
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: bkn-sample-studio
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: bkn-sample-studio
rules:
  - apiGroups: [""]
    resources: ["namespaces"]
    resourceNames: ["openbkn-samples"]
    verbs: ["get", "update", "patch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: bkn-sample-studio
subjects:
  - kind: ServiceAccount
    name: bkn-sample-studio
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: bkn-sample-studio
