apiVersion: v1
kind: Service
metadata:
  name: bkn-sample-studio
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: bkn-sample-studio
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
