replicaCount: 1

image:
  repository: ghcr.io/openbkn-ai/bkn-sample-studio
  tag: "__VERSION__"
  pullPolicy: IfNotPresent

dataImage:
  tag: "__VERSION__"

service:
  port: 8080

ingress:
  enabled: true
  ingressClass: class-443
  path: /api/studio

safeURL: http://bkn-safe:3000
baseURL: ""

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 500m
    memory: 256Mi
